/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as QuoteIndexRouteImport } from './routes/quote/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as IntroductionIndexRouteImport } from './routes/introduction/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ServicesLayoutRouteImport } from './routes/services/_layout'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as QuoteLayoutRouteImport } from './routes/quote/_layout'
import { Route as ProjectsLayoutRouteImport } from './routes/projects/_layout'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProductsLayoutRouteImport } from './routes/products/_layout'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as IntroductionLayoutRouteImport } from './routes/introduction/_layout'
import { Route as ContactLayoutRouteImport } from './routes/contact/_layout'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout/users'
import { Route as AdminLayoutStatisticsRouteImport } from './routes/admin/_layout/statistics'
import { Route as AdminLayoutServicesRouteImport } from './routes/admin/_layout/services'
import { Route as AdminLayoutQuotesRouteImport } from './routes/admin/_layout/quotes'
import { Route as AdminLayoutProjectsRouteImport } from './routes/admin/_layout/projects'
import { Route as AdminLayoutProductsRouteImport } from './routes/admin/_layout/products'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout/dashboard'
import { Route as AdminLayoutContactUsRouteImport } from './routes/admin/_layout/contact-us'
import { Route as AdminLayoutContactRouteImport } from './routes/admin/_layout/contact'
import { Route as AdminLayoutCategoriesRouteImport } from './routes/admin/_layout/categories'

const ServicesRouteImport = createFileRoute('/services')()
const QuoteRouteImport = createFileRoute('/quote')()
const ProjectsRouteImport = createFileRoute('/projects')()
const ProductsRouteImport = createFileRoute('/products')()
const IntroductionRouteImport = createFileRoute('/introduction')()
const ContactRouteImport = createFileRoute('/contact')()
const AuthRouteImport = createFileRoute('/auth')()
const AdminRouteImport = createFileRoute('/admin')()

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionRoute = IntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuoteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const IntroductionIndexRoute = IntroductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntroductionRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesLayoutRoute = ServicesLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteLayoutRoute = QuoteLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => QuoteRoute,
} as any)
const ProjectsLayoutRoute = ProjectsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLayoutRoute = ProductsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroductionLayoutRoute = IntroductionLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => IntroductionRoute,
} as any)
const ContactLayoutRoute = ContactLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ContactRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutStatisticsRoute = AdminLayoutStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutServicesRoute = AdminLayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutQuotesRoute = AdminLayoutQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProjectsRoute = AdminLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutProductsRoute = AdminLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContactUsRoute = AdminLayoutContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutContactRoute = AdminLayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCategoriesRoute = AdminLayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/contact': typeof ContactLayoutRoute
  '/introduction': typeof IntroductionLayoutRoute
  '/products/$id': typeof ProductsIdRoute
  '/products': typeof ProductsLayoutRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsLayoutRoute
  '/quote': typeof QuoteLayoutRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesLayoutRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/introduction/': typeof IntroductionIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/categories': typeof AdminLayoutCategoriesRoute
  '/admin/contact': typeof AdminLayoutContactRoute
  '/admin/contact-us': typeof AdminLayoutContactUsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/products': typeof AdminLayoutProductsRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/quotes': typeof AdminLayoutQuotesRoute
  '/admin/services': typeof AdminLayoutServicesRoute
  '/admin/statistics': typeof AdminLayoutStatisticsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/contact': typeof ContactIndexRoute
  '/introduction': typeof IntroductionIndexRoute
  '/products/$id': typeof ProductsIdRoute
  '/products': typeof ProductsIndexRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/quote': typeof QuoteIndexRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/categories': typeof AdminLayoutCategoriesRoute
  '/admin/contact': typeof AdminLayoutContactRoute
  '/admin/contact-us': typeof AdminLayoutContactUsRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/products': typeof AdminLayoutProductsRoute
  '/admin/projects': typeof AdminLayoutProjectsRoute
  '/admin/quotes': typeof AdminLayoutQuotesRoute
  '/admin/services': typeof AdminLayoutServicesRoute
  '/admin/statistics': typeof AdminLayoutStatisticsRoute
  '/admin/users': typeof AdminLayoutUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/contact': typeof ContactRouteWithChildren
  '/contact/_layout': typeof ContactLayoutRoute
  '/introduction': typeof IntroductionRouteWithChildren
  '/introduction/_layout': typeof IntroductionLayoutRoute
  '/products/$id': typeof ProductsIdRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/_layout': typeof ProductsLayoutRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/_layout': typeof ProjectsLayoutRoute
  '/quote': typeof QuoteRouteWithChildren
  '/quote/_layout': typeof QuoteLayoutRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/_layout': typeof ServicesLayoutRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/introduction/': typeof IntroductionIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/_layout/categories': typeof AdminLayoutCategoriesRoute
  '/admin/_layout/contact': typeof AdminLayoutContactRoute
  '/admin/_layout/contact-us': typeof AdminLayoutContactUsRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/products': typeof AdminLayoutProductsRoute
  '/admin/_layout/projects': typeof AdminLayoutProjectsRoute
  '/admin/_layout/quotes': typeof AdminLayoutQuotesRoute
  '/admin/_layout/services': typeof AdminLayoutServicesRoute
  '/admin/_layout/statistics': typeof AdminLayoutStatisticsRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/contact'
    | '/introduction'
    | '/products/$id'
    | '/products'
    | '/projects/$slug'
    | '/projects'
    | '/quote'
    | '/services/$slug'
    | '/services'
    | '/admin/'
    | '/contact/'
    | '/introduction/'
    | '/products/'
    | '/projects/'
    | '/quote/'
    | '/services/'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/contact-us'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/contact'
    | '/introduction'
    | '/products/$id'
    | '/products'
    | '/projects/$slug'
    | '/projects'
    | '/quote'
    | '/services/$slug'
    | '/services'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/contact-us'
    | '/admin/dashboard'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/quotes'
    | '/admin/services'
    | '/admin/statistics'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_layout'
    | '/auth'
    | '/auth/_layout'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/contact'
    | '/contact/_layout'
    | '/introduction'
    | '/introduction/_layout'
    | '/products/$id'
    | '/products'
    | '/products/_layout'
    | '/projects/$slug'
    | '/projects'
    | '/projects/_layout'
    | '/quote'
    | '/quote/_layout'
    | '/services/$slug'
    | '/services'
    | '/services/_layout'
    | '/admin/'
    | '/contact/'
    | '/introduction/'
    | '/products/'
    | '/projects/'
    | '/quote/'
    | '/services/'
    | '/admin/_layout/categories'
    | '/admin/_layout/contact'
    | '/admin/_layout/contact-us'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/products'
    | '/admin/_layout/projects'
    | '/admin/_layout/quotes'
    | '/admin/_layout/services'
    | '/admin/_layout/statistics'
    | '/admin/_layout/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRouteWithChildren
  IntroductionRoute: typeof IntroductionRouteWithChildren
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QuoteRoute: typeof QuoteRouteWithChildren
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction': {
      id: '/introduction'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/quote/': {
      id: '/quote/'
      path: '/'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof QuoteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/introduction/': {
      id: '/introduction/'
      path: '/'
      fullPath: '/introduction/'
      preLoaderRoute: typeof IntroductionIndexRouteImport
      parentRoute: typeof IntroductionRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof ContactRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/_layout': {
      id: '/services/_layout'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLayoutRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/_layout': {
      id: '/quote/_layout'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteLayoutRouteImport
      parentRoute: typeof QuoteRoute
    }
    '/projects/_layout': {
      id: '/projects/_layout'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLayoutRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/_layout': {
      id: '/products/_layout'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLayoutRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introduction/_layout': {
      id: '/introduction/_layout'
      path: '/introduction'
      fullPath: '/introduction'
      preLoaderRoute: typeof IntroductionLayoutRouteImport
      parentRoute: typeof IntroductionRoute
    }
    '/contact/_layout': {
      id: '/contact/_layout'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLayoutRouteImport
      parentRoute: typeof ContactRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/statistics': {
      id: '/admin/_layout/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminLayoutStatisticsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/services': {
      id: '/admin/_layout/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminLayoutServicesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/quotes': {
      id: '/admin/_layout/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminLayoutQuotesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/projects': {
      id: '/admin/_layout/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminLayoutProjectsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/products': {
      id: '/admin/_layout/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminLayoutProductsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/contact-us': {
      id: '/admin/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/admin/contact-us'
      preLoaderRoute: typeof AdminLayoutContactUsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/contact': {
      id: '/admin/_layout/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminLayoutContactRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/categories': {
      id: '/admin/_layout/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminLayoutCategoriesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutCategoriesRoute: typeof AdminLayoutCategoriesRoute
  AdminLayoutContactRoute: typeof AdminLayoutContactRoute
  AdminLayoutContactUsRoute: typeof AdminLayoutContactUsRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutProductsRoute: typeof AdminLayoutProductsRoute
  AdminLayoutProjectsRoute: typeof AdminLayoutProjectsRoute
  AdminLayoutQuotesRoute: typeof AdminLayoutQuotesRoute
  AdminLayoutServicesRoute: typeof AdminLayoutServicesRoute
  AdminLayoutStatisticsRoute: typeof AdminLayoutStatisticsRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutCategoriesRoute: AdminLayoutCategoriesRoute,
  AdminLayoutContactRoute: AdminLayoutContactRoute,
  AdminLayoutContactUsRoute: AdminLayoutContactUsRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutProductsRoute: AdminLayoutProductsRoute,
  AdminLayoutProjectsRoute: AdminLayoutProjectsRoute,
  AdminLayoutQuotesRoute: AdminLayoutQuotesRoute,
  AdminLayoutServicesRoute: AdminLayoutServicesRoute,
  AdminLayoutStatisticsRoute: AdminLayoutStatisticsRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ContactRouteChildren {
  ContactLayoutRoute: typeof ContactLayoutRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const ContactRouteChildren: ContactRouteChildren = {
  ContactLayoutRoute: ContactLayoutRoute,
  ContactIndexRoute: ContactIndexRoute,
}

const ContactRouteWithChildren =
  ContactRoute._addFileChildren(ContactRouteChildren)

interface IntroductionRouteChildren {
  IntroductionLayoutRoute: typeof IntroductionLayoutRoute
  IntroductionIndexRoute: typeof IntroductionIndexRoute
}

const IntroductionRouteChildren: IntroductionRouteChildren = {
  IntroductionLayoutRoute: IntroductionLayoutRoute,
  IntroductionIndexRoute: IntroductionIndexRoute,
}

const IntroductionRouteWithChildren = IntroductionRoute._addFileChildren(
  IntroductionRouteChildren,
)

interface ProductsRouteChildren {
  ProductsLayoutRoute: typeof ProductsLayoutRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsLayoutRoute: ProductsLayoutRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsLayoutRoute: typeof ProjectsLayoutRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsLayoutRoute: ProjectsLayoutRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface QuoteRouteChildren {
  QuoteLayoutRoute: typeof QuoteLayoutRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
}

const QuoteRouteChildren: QuoteRouteChildren = {
  QuoteLayoutRoute: QuoteLayoutRoute,
  QuoteIndexRoute: QuoteIndexRoute,
}

const QuoteRouteWithChildren = QuoteRoute._addFileChildren(QuoteRouteChildren)

interface ServicesRouteChildren {
  ServicesLayoutRoute: typeof ServicesLayoutRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesLayoutRoute: ServicesLayoutRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRouteWithChildren,
  IntroductionRoute: IntroductionRouteWithChildren,
  ProductsIdRoute: ProductsIdRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QuoteRoute: QuoteRouteWithChildren,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
